"""auto vote

Revision ID: 3af1df5462c3
Revises: 2aa0c56cec9d
Create Date: 2024-01-22 12:52:25.298632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af1df5462c3'
down_revision = '2aa0c56cec9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint('posts_email_key', 'posts', type_='unique')
    op.drop_column('posts', 'password')
    op.drop_column('posts', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('posts_email_key', 'posts', ['email'])
    op.drop_column('posts', 'title')
    op.drop_table('votes')
    # ### end Alembic commands ###
